#!/usr/bin/env python3
import sys
from coinbase.wallet.client import Client


def main():
    with open('etc/.api', 'r') as infile:
        lines = [line for line in infile]
    key    = str(lines[0]).strip()
    secret = str(lines[1]).strip()

    client = Client(key, secret, api_version='2017-10-09')
    print(client.get_historic_prices(currency_pair='ETH-USD'))

    accountDict = dict()
    accounts = client.get_accounts()
    for account in accounts.data:
      balance = account.balance
      print("%s: %s %s" % (account.name, balance.amount, balance.currency))
      print(account)
      accountDict[account.name] = account
      #print(account.get_transactions())

    #buy = client.buy(accountDict['LTC Wallet'].id,
    #amount=".5",
    #currency="LTC")
                     #payment_method=accountDict['USD Wallet'].id)
                     #payment_method="83562370-3e5c-51db-87da-752af5ab9559")
    #print(buy)
    sell = client.sell(accountDict['LTC Wallet'].id,
                       amount=accountDict['LTC Wallet'].balance.amount,
                       currency='LTC')
    print(sell)

    '''

    buy = client.buy('2bbf394c-193b-5b2a-9155-3b4732659ede',
                     amount="10",
                     currency="BTC",
                     payment_method="83562370-3e5c-51db-87da-752af5ab9559")
    sell = client.sell('2bbf394c-193b-5b2a-9155-3b4732659ede',
                       amount="10",
                       currency="BTC",
                       payment_method="83562370-3e5c-51db-87da-752af5ab9559")
    '''
    return 0

if __name__ == '__main__':
    sys.exit(main())
