#!/usr/bin/env python3
import sys
from time import time
from api import init_client

ROUGH_FEE = 0.01468064

def main():

    client = init_client()

    # Give the program some arbitrary bitcoin threshold
    threshold = 8100

    accountDict = dict()
    accounts = client.get_accounts()
    for account in accounts.data:
      accountDict[account.name] = account

    startTime = time()
    while True:
        currentTime = time()
        price = float(client.get_sell_price(currency_pair='BTC-USD')['amount'])
        print('Elapsed: {}'.format(currentTime - startTime))
        startTime = currentTime
        #print('threshold: {}'.format(threshold))
        #print('price : {}'.format(price))
        if price < threshold:
            print('SELLING ALL BITCOIN')
            sell = client.sell(accountDict['BTC Wallet'].id,
                               amount=accountDict['BTC Wallet'].balance.amount,
                               currency='BTC')
        else:
            print('Bitcoin is {} above threshold'.format(price - threshold))

    '''
    #buy = client.buy(accountDict['LTC Wallet'].id,
    #amount=".5",
    #currency="LTC")
                     #payment_method=accountDict['USD Wallet'].id)
                     #payment_method="83562370-3e5c-51db-87da-752af5ab9559")
    #print(buy)
    sell = client.sell(accountDict['LTC Wallet'].id,
                       amount=accountDict['LTC Wallet'].balance.amount,
                       currency='LTC')
    print(sell)


    buy = client.buy('2bbf394c-193b-5b2a-9155-3b4732659ede',
                     amount="10",
                     currency="BTC",
                     payment_method="83562370-3e5c-51db-87da-752af5ab9559")
    sell = client.sell('2bbf394c-193b-5b2a-9155-3b4732659ede',
                       amount="10",
                       currency="BTC",
                       payment_method="83562370-3e5c-51db-87da-752af5ab9559")
    '''
    return 0

if __name__ == '__main__':
    sys.exit(main())
